spring.application.name=CloudBalance

spring.datasource.url=jdbc:mysql://localhost:3306/cloudBalanceDb
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.username=yogesh
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
jwtSecret=53485HKRFDJBVMXBVSJFKUWEOIFHNSDJBVJDRTRBDFDVXCZRA
#logging.level.org.springframework.security=DEBUG


snowflake.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver
snowflake.datasource.jdbc-url=jdbc:snowflake://jgwazim-wu66490.snowflakecomputing.com
?db=snowflake_learning_db
&schema=AWS_CUR
&warehouse=snowflake_learning_wh
&role=cost_db_readonly
&disableGcpCloudAuth=true
&disableAwsCloudAuth=true
&disableAzureCloudAuth=true
snowflake.datasource.username=cost_read_user
snowflake.datasource.password=aws_cost_report_read_only
snowflake.datasource.maximum-pool-size=10
snowflake.datasource.pool-name=SnowflakeHikariPool
